Addition of package extraction and build guarding.

diff --git a/pkg-scripts/12-diffutils b/pkg-scripts/12-diffutils
--- a/pkg-scripts/12-diffutils
+++ b/pkg-scripts/12-diffutils
@@ -1,7 +1,9 @@
 #!/usr/bin/env bash
 
-# Configuration failure if prefix path doesn't exist
-./configure --prefix=$(realpath "../../rootfs/usr")
+if ! [[ -e Makefile ]]; then
+    # Configuration failure if prefix path doesn't exist
+    ./configure --prefix=$(realpath "../../rootfs/usr")
+fi
 
 make LDFLAGS='-static' install
 
